---
  promotions:
    development:
      promote_to:
        - "testing"
      targeted_names:
      days_in_catalog: 3
    testing:
      promote_to:
        - "production"
      days_in_catalog: 7
      excluded_names:
      targeted_names:
  global_targeted_names:
    - "Firefox"
    - "GoogleChrome"





